import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ensureSchema} from "./lib/init";
import Navbar from "@/components/Navbar";

//Initalize DB
ensureSchema().catch(console.error);

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Job Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <header style={{padding: "12px 16px", borderBottom: "1px solid #eaeaea"}}>
            <Navbar/>
        </header>
        <div className="flex min-h-screen items-center justify-center font-sans bg-background">
            <main className="min-h-screen w-full py-2 px-16">
                <div className="w-full items-center gap-6 text-center sm:items-start sm:text-left">
                    {children}
                </div>
            </main>
        </div>
        </body>
        </html>
    );
}
