import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ensureSchema} from "./lib/init";
import Link from "next/link";

//Initalize DB
ensureSchema().catch(console.error);

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <header style={{padding: "12px 16px", borderBottom: "1px solid #eaeaea"}}>
            <nav style={{display: "flex", gap: "16px" }}>
                <Link href="/">Home</Link>
                <Link href="/jobs">Jobs</Link>
                <Link href="/jobs/new">Add Job</Link>
            </nav>
        </header>
        <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">

                <div className="flex flex-col items-center gap-6 text-center sm:items-start sm:text-left">
                    {children}
                </div>

            </main>
        </div>
        </body>
        </html>
    );
}
