import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ensureSchema} from "./lib/init";
import Navbar from "@/components/Navbar";

//Initalize DB
ensureSchema().catch(console.error);

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Job Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <header className="border-b border-gray-200 px-4 py-3 dark:border-gray-800 sm:px-6">
            <Navbar/>
        </header>
        <div className="flex min-h-screen items-start justify-center bg-background font-sans">
            <main className="min-h-screen w-full px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
                <div className="w-full items-center gap-6 text-center sm:items-start sm:text-left">
                    {children}
                </div>
            </main>
        </div>
        </body>
        </html>
    );
}
